src/Entity/Shows.php
<?php

namespace App\Entity;

use App\Repository\ShowsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=ShowsRepository::class)
 * @ORM\Table(name="`shows`")
 * @UniqueEntity("slug")

 */
class Shows
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_url;

    /**
     * @ORM\ManyToOne(targetEntity=Locations::class, inversedBy="shows")
	 * @JoinColumn(onDelete="RESTRICT")
     */
    private $location;

    /**
     * @ORM\Column(type="boolean")
     */
    private $bookable;

    /**
     * @ORM\Column(type="decimal", precision=12, scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity=Representations::class, mappedBy="the_show", orphanRemoval=true)
     */
    private $representations;

    /**
     * @ORM\ManyToMany(targetEntity=ArtistsTypes::class, inversedBy="shows")
     */
    private $artistsTypes;

    public function __construct()
    {
        $this->representations = new ArrayCollection();
        $this->artistsTypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getLocation(): ?Locations
    {
        return $this->location;
    }

    public function setLocation(?Locations $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getBookable(): ?bool
    {
        return $this->bookable;
    }

    public function setBookable(bool $bookable): self
    {
        $this->bookable = $bookable;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, Representations>
     */
    public function getRepresentations(): Collection
    {
        return $this->representations;
    }

    public function addRepresentation(Representations $representation): self
    {
        if (!$this->representations->contains($representation)) {
            $this->representations[] = $representation;
            $representation->setTheShow($this);
        }

        return $this;
    }

    public function removeRepresentation(Representations $representation): self
    {
        if ($this->representations->removeElement($representation)) {
            // set the owning side to null (unless already changed)
            if ($representation->getTheShow() === $this) {
                $representation->setTheShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ArtistsTypes>
     */
    public function getArtistsTypes(): Collection
    {
        return $this->artistsTypes;
    }

    public function addArtistsType(ArtistsTypes $artistsType): self
    {
        if (!$this->artistsTypes->contains($artistsType)) {
            $this->artistsTypes[] = $artistsType;
        }

        return $this;
    }

    public function removeArtistsType(ArtistsTypes $artistsType): self
    {
        $this->artistsTypes->removeElement($artistsType);

        return $this;
    }
	  
   

}

src/Controller/ShowsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Shows;
use App\Entity\Users;
use App\Entity\Roles;
class ShowsController extends AbstractController
{
    /**
     * @Route("/shows", name="app_shows")
     */
    public function index(): Response
    {
        if (!$this->getUser()->getRoles()) 
		{
			 
			  $name= $this->getUser()->getUsername();
		      $role='ROLE_MEMBER';
			  
		}
        else    
        {
			 
			  $name= $this->getUser()->getUsername();
		      $role= implode($this->getUser()->getRoles());
		}	 
        $repository = $this->getDoctrine()->getRepository(Shows::class);
        $shows = $repository->findAll();
        
        return $this->render('shows/index.html.twig', [
            'shows' => $shows,
            'resource' => 'spectacles',
			'nom' => $name,
			
        ]);

    }
	 /**
     * @Route("/shows/{id}", name="shows_show")
     */
    public function show($id)
    {
        $name= $this->getUser()->getUsername();
        $repository = $this->getDoctrine()->getRepository(Shows::class);
        $show = $repository->find($id);
        return $this->render('shows/show.html.twig', [
            'show' => $show,
			'nom' => $name,
			
        ]);
    }

}

templates/shows/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ resource}}{% endblock %}
{% block stylesheets %}
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="{{asset('datatables/DataTables-1.11.5/css/jquery.dataTables.min.css')}}"/>
<!-- DataTables Responsive CSS -->
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 14px/1.5 sans-serif; }
</style>
{% endblock %}                
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ resource }}</h1>

    <table id="table_shows" class="display" >
        <thead>
            <tr>
                 <th>Titre</th>
				 <th>Auteur</th>
				 <th>Lieu</th>
				 <th>Representations</th>
				 <th>Prix</th>
                 <th>Réservable</th>
            </tr>
        </thead>
        <tbody>
        {% for show  in shows %}
            <tr>
                  <td><a href="{{ path('shows_show', { id: show.id }) }}">{{ show.title|title }}</a></td>
			      <td>              
            {% for collaborateur in show.artistsTypes %}
			{% if collaborateur.type.type=='auteur' %}
                
				   {{ collaborateur.artist.firstname }}
				   {{ collaborateur.artist.lastname }}
					
								
            {% endif %}             
            {% endfor %}
                 </td>
			{% if show.location %}
				  <td>{{ show.location.designation  }}</td>
			{% else %}
                 <td> <em>à déterminer</em></td> 
            {% endif %}
				<td>{{ show.representations|length }}</td>
                <td>{{ show.price|number_format(2, ',', '.') }}&nbsp;&euro;</td>
            {% if show.bookable %}
                <td>Oui</td>
            {% else %}
                <td>Non</td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        
    </table>

    <p>Total: {{ shows|length }} spectacles.</p></div>
{% endblock %}
{% block javascripts %}
<script type="text/javascript" src="{{ asset('datatables/jQuery-3.6.0/jquery-3.6.0.min.js') }}"> </script>
<script type="text/javascript" src="{{ asset('datatables/DataTables-1.11.5/js/jquery.dataTables.min.js') }}"> </script>
<script type="text/javascript" src="{{ asset('datatables/DataTables-1.11.5/js/dataTables.bootstrap.min.js') }}"> </script>
<script>
$(document).ready( function () {
    $('#table_shows').DataTable({
            responsive: true
    });
} );   
</script>
{% endblock %} 

templates/shows/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'un spectacle{% endblock %}

{% block body %}
<nav><a href="{{ path('app_shows') }}">Retour à l'index</a></nav>
    <article>
        <h2><strong>spectacle:</strong> {{ show.title }}</h2>

        {% if show.posterUrl %}
        <p><img src="{{ asset('images/' ~ show.posterUrl) }}" alt="{{ show.title }}" width="200"></p>
        {% else %}
        <canvas width="200" height="100" style="border:1px solid #000000;"></canvas>
        {% endif %}
		
        {% if show.description %}
        <p><strong>Description:</strong> {{ show.description }}</p>
        {% endif %}
		
        {% if show.location %}
        <p><strong>Lieu de création:</strong> {{ show.location.designation }}</p>
        {% endif %}
        
       <p><strong>Prix:</strong> {{ show.price }} €</p>

        {% if show.bookable %}
        <p><em>Réservable</em></p>
        {% else %}
        <p><em>Non réservable</em></p>
        {% endif %}
		        <h2>Liste des représentations</h2>
        {% if show.representations|length>=1 %}
        <ul>
            {% for representation in show.representations %}
                <li>{{ representation.schedule|date('d/m/Y G:i:s') }}</li>              
            {% endfor %}
        </ul>
        {% else %}
        <p>Aucune représentation</p>
        {% endif %}
		
                 <h2>Liste des artistes</h2>
                    <ul>
            {% for collaborateur in show.artistsTypes %}
                <li>
                    {{ collaborateur.artist.firstname }}
                    {{ collaborateur.artist.lastname }}
                    ({{ collaborateur.type.type }})
                </li>              
            {% endfor %}
        </ul>
  

    </article>

    
{% endblock %}