src/Entity/Representations.php
<?php

namespace App\Entity;

use App\Repository\RepresentationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
/**
 * @ORM\Entity(repositoryClass=RepresentationsRepository::class)
 * @ORM\Table(name="representations")
 */
class Representations
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Shows::class, inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="show_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $the_show;

    /**
     * @ORM\Column(type="datetime")
     */
    private $schedule;

    /**
     * @ORM\ManyToOne(targetEntity=Locations::class, inversedBy="representations")
	 * @ORM\JoinColumn(name="location_id", referencedColumnName="id", onDelete="RESTRICT") 
     */
    private $the_location;

    /**
     * @ORM\OneToMany(targetEntity=RepresentationsUsers::class, mappedBy="representations", orphanRemoval=true)
     */
    private $representationsusers;

    public function __construct()
    {
        $this->representationsusers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?Shows
    {
        return $this->the_show;
    }

    public function setTheShow(?Shows $the_show): self
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getSchedule(): ?\DateTimeInterface
    {
        return $this->schedule;
    }

    public function setSchedule(\DateTimeInterface $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getTheLocation(): ?Locations
    {
        return $this->the_location;
    }

    public function setTheLocation(?Locations $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }

    /**
     * @return Collection<int, RepresentationsUsers>
     */
    public function getRepresentationsusers(): Collection
    {
        return $this->representationsusers;
    }

    public function addRepresentationsuser(RepresentationsUsers $representationsuser): self
    {
        if (!$this->representationsusers->contains($representationsuser)) {
            $this->representationsusers[] = $representationsuser;
            $representationsuser->setRepresentations($this);
        }

        return $this;
    }

    public function removeRepresentationsuser(RepresentationsUsers $representationsuser): self
    {
        if ($this->representationsusers->removeElement($representationsuser)) {
            // set the owning side to null (unless already changed)
            if ($representationsuser->getRepresentations() === $this) {
                $representationsuser->setRepresentations(null);
            }
        }

        return $this;
    }
}

src/Entity/RepresentationsUsers.php
<?php

namespace App\Entity;

use App\Repository\RepresentationsUsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
/**
 * @ORM\Entity(repositoryClass=RepresentationsUsersRepository::class)
 * @ORM\Table(name="representationsusers")
 */
class RepresentationsUsers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Representations::class, inversedBy="representationsusers")
     * @ORM\JoinColumn(nullable=false, name="representations_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $representations;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="usersrepresentations")
     * @ORM\JoinColumn(nullable=false, name="users_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $places;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRepresentations(): ?Representations
    {
        return $this->representations;
    }

    public function setRepresentations(?Representations $representations): self
    {
        $this->representations = $representations;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getPlaces(): ?string
    {
        return $this->places;
    }

    public function setPlaces(string $places): self
    {
        $this->places = $places;

        return $this;
    }
}

src/Controller/RepresentationsUsersController.php
<?php

namespace App\Controller;

use App\Form\ReservationType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\RepresentationsUsers;
use App\Entity\Users;
use App\Entity\Shows;
use App\Entity\Representations;

class RepresentationsUsersController extends AbstractController
{
    
	/**
     * @Route("/representations_users", name="app_representations_users")
     */
    public function index()
    {
		$numero=$this->getUser()->getId();
		$name= $this->getUser()->getUsername();
        $repository = $this->getDoctrine()->getRepository(RepresentationsUsers::class);
        $representationusers = $repository->findBy(array('users' => $numero));

        return $this->render('representations_users/index.html.twig', [
            'representationusers' => $representationusers,
			'resource' => 'Réservations  :',
			'nom' => $name,
        ]);
    }
	/**
     * @Route("/representations_users/{id}", name="representations_users_show")
     */
	 public function show($id)
    {
		$name= $this->getUser()->getUsername();
        $repository = $this->getDoctrine()->getRepository(RepresentationsUsers::class);
        $representationuser = $repository->find($id);

        return $this->render('representations_users/show.html.twig', [
            'representationuser' => $representationuser,
			'resource' => 'Réservation de :',
			'nom' => $name,
        ]);
    }
	/**
     * @Route("/representations/users/{id}", name="representations_users_reservation")
     */
	  public function reservation(Request $request, $id):response
	  {
		     
		     $name= $this->getUser()->getUsername();
		     $reservation= new RepresentationsUsers();
			 $form = $this->createForm(ReservationType::class, $reservation);
			 $form->handleRequest($request);
             
            if ($form->isSubmitted() && $form->isValid()) 
		      {
				
				$user = $this->getUser();
                $repository = $this->getDoctrine()->getRepository(Representations::class);
                $representation = $repository->find($id);
                $em = $this->getDoctrine()->getManager();
				
                $reservation->setUsers($user); 
			    $reservation->setRepresentations($representation);
				 $em->persist($reservation);             
				 $em->flush();
                return $this->redirect($this->generateUrl('app_representations_users'));
        
			  }
             return $this->render('representations_users/reservation.html.twig', [
			 'resource' => 'Reservation',
             'formindex' => $form->createView()
        ]);			  
	  }
}

templates/representations_users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des réservations{% endblock %}

{% block body %}
    <h1>Liste de mes {{ resource }}</h1>
    
     <ul>
    {% for representationuser in representationusers %}
	   <li><h4>Réservation du {{ representationuser.representations.schedule|date('d/m/Y') }} à {{ representationuser.representations.schedule|date('G:i') }}</h4></li>
	   <li> <h4> places :{{ representationuser .places }}</h4></li>
	   <a href="{{ path('representations_users_show', { id:representationuser .id }) }}">Détails</a>
    {% endfor %}
    </ul>

{% endblock %}

templates/representations_users/reservation.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Projet réservations </title>
		 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        
        
         <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
                <h3 class="my-0 mr-md-auto font-weight-normal" style="margin-right:300px;">Projet Réservations</h3>
            <form class="form-inline mt-2 mt-md-0" style="margin-right:200px;">
			    <p class="d-flex flex-column flex-md-row align-items-center">
		              <input class="form-control mr-sm-2" type="text" placeholder="Rechercher" style=";" aria-label="Search" /> 
			          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style=";">🔍</button>
           	    </p> 		
            </form>
               
        </div>
     
                {% block stylesheets %}
				<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="{{asset('datatables/DataTables-1.11.5/css/jquery.dataTables.min.css')}}"/>
<!-- DataTables Responsive CSS -->
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 14px/1.5 sans-serif; }
</style>
				{% endblock %}
    </head>
 <body>
	      <div class="container">
{% block body %}
    
        <h1>Réservation</h1>
        {{ form(formindex) }}
   
{% endblock %}
</div>
</body>
    <footer>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h4 class="my-0 mr-md-auto font-weight-normal" style="margin-left:500px;">Projet Réservations icc/EPFC 2022</h4>
        </div>
    </footer>
</html>

templates/representations_users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}réservation d'un utilisateur{% endblock %}

{% block body %}

              <h1>{{ resource }}</h1>
        <h2>{{ representationuser.users.firstname }} {{ representationuser.users.lastname }}</h2>
    
        <h4>Représentation du {{ representationuser.representations.schedule|date('d/m/Y') }} à {{ representationuser.representations.schedule|date('G:i') }}</h4>
        <h4> titre : {{representationuser.representations.theShow.title}}</h4>
		<h4> lieu : {% if representationuser.representations.theLocation %}
		           {{representationuser.representations.theLocation.designation}}
				   {% else %}
                     <em>à déterminer</em> 
                   {% endif %}
				   </h4>
		<h4> places : {{representationuser.places}}</h4>
{% endblock %}